name: codetail-web

services:
  web:
    build: .
    container_name: codetail_web
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
      - PORT=3001
    ports:
      - "127.0.0.1:3001:3001"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
