import { CodeBlock } from "@/components/blog/interactive/code-block";

export function FunctoolsModernSection() {
  return (
    <section>
      <h2
        id="functools-modern"
        className="text-xl font-semibold text-brand-text mt-12 mb-4 scroll-mt-24"
      >
        functools: partial, reduce, and total_ordering
      </h2>

      <p className="text-[15px] leading-relaxed text-brand-text/90 mb-4">
        Beyond{" "}
        <code className="font-mono text-[13px] bg-brand-surface px-1.5 py-0.5 rounded">
          @cache
        </code>
        , the{" "}
        <code className="font-mono text-[13px] bg-brand-surface px-1.5 py-0.5 rounded">
          functools
        </code>{" "}
        module has several utilities that remove boilerplate from common patterns.
      </p>

      <h3 className="text-base font-semibold text-brand-text mt-6 mb-3">
        partial: pre-fill function arguments
      </h3>

      <CodeBlock
        code={`from functools import partial

def power(base: float, exponent: float) -> float:
    return base ** exponent

# Before: write a one-liner wrapper every time
def square(n: float) -> float:
    return power(n, 2)

# After: partial freezes some arguments
square = partial(power, exponent=2)
cube   = partial(power, exponent=3)

print(square(4))   # 16.0
print(cube(3))     # 27.0

# Practical: pre-configure a logging function
import logging
logging.basicConfig(level=logging.DEBUG)

debug = partial(logging.log, logging.DEBUG)
debug("Server started on port %d", 8080)`}
        output={`16.0
27.0
DEBUG:root:Server started on port 8080`}
      />

      <h3 className="text-base font-semibold text-brand-text mt-8 mb-3">
        total_ordering: define two methods, get six
      </h3>

      <CodeBlock
        code={`from functools import total_ordering

# Without total_ordering: must implement __lt__, __le__, __gt__, __ge__, __eq__
# With total_ordering: define __eq__ and one of the ordering methods

@total_ordering
class Version:
    def __init__(self, major: int, minor: int, patch: int) -> None:
        self.major = major
        self.minor = minor
        self.patch = patch

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Version):
            return NotImplemented
        return (self.major, self.minor, self.patch) == (other.major, other.minor, other.patch)

    def __lt__(self, other: "Version") -> bool:
        return (self.major, self.minor, self.patch) < (other.major, other.minor, other.patch)

v1 = Version(1, 2, 3)
v2 = Version(1, 3, 0)

print(v1 < v2)    # True  -- from __lt__
print(v1 > v2)    # False -- generated by total_ordering
print(v1 <= v2)   # True  -- generated
print(sorted([v2, v1]))  # [Version(1,2,3), Version(1,3,0)]`}
        output={`True
False
True
[<Version 1.2.3>, <Version 1.3.0>]`}
      />

      <p className="text-[15px] leading-relaxed text-brand-text/90 mt-6 mb-4">
        One last note: if ordering is the primary reason you are writing a class,{" "}
        <code className="font-mono text-[13px] bg-brand-surface px-1.5 py-0.5 rounded">
          @dataclass(order=True)
        </code>{" "}
        generates all six comparison methods automatically from the field order. Reserve{" "}
        <code className="font-mono text-[13px] bg-brand-surface px-1.5 py-0.5 rounded">
          @total_ordering
        </code>{" "}
        for classes with custom comparison logic.
      </p>
    </section>
  );
}
