const KEY_RULES = [
  {
    rule: "The client owns the key",
    detail:
      "The key must be generated by the client, not the server. A server-generated key provides no protection: the second request has no key to send.",
  },
  {
    rule: "Use UUID v4",
    detail:
      "Keys must be random and unique per operation. UUID v4 has 2^122 possible values. Collision probability is negligible for any realistic request volume.",
  },
  {
    rule: "Set a TTL on stored results",
    detail:
      "Idempotency state does not need to live forever. A 24-hour TTL covers any reasonable retry window. After that, a duplicate request is treated as a new operation.",
  },
  {
    rule: "Store the full response, not a flag",
    detail:
      "The client needs the original result on retry: the order ID, charge ID, or entity that was created. A flag that says 'seen' is useless. Store the serialized response body.",
  },
];

const PATTERNS = [
  {
    pattern: "Idempotency key (Redis)",
    when: "HTTP endpoints where the client retries on network failure",
    tradeoff: "Requires client cooperation and a shared store (Redis). Keys expire after TTL so retries outside the window are treated as new requests.",
  },
  {
    pattern: "Database UPSERT",
    when: "Record creation where a natural unique key exists in the data",
    tradeoff: "Zero additional infrastructure. Only works when the operation maps cleanly to a single row with a meaningful unique constraint.",
  },
  {
    pattern: "Redis SET NX",
    when: "High-throughput message consumers or operations where checking the database on every message is too slow",
    tradeoff: "Fast and lightweight. State is lost if Redis restarts without persistence. Use as a fast path in front of a durable check.",
  },
];

export function ImplementingSection() {
  return (
    <section>
      <h2 id="implementing" className="text-xl font-semibold mt-12 mb-4 scroll-mt-24">
        Implementing Idempotency
      </h2>

      <p className="text-[15px] leading-relaxed text-foreground/90 mb-4">
        For operations that are not naturally idempotent (POST, PATCH, message consumers),
        idempotency must be added at the application layer. Three patterns cover most
        cases: idempotency keys for request-level deduplication, database UPSERT for
        record-level deduplication, and Redis SET NX for fast pre-database deduplication.
      </p>

      <h3 className="text-base font-semibold mt-8 mb-3">Idempotency keys</h3>

      <p className="text-[15px] leading-relaxed text-foreground/90 mb-4">
        The client generates a UUID before sending the request and includes it in an
        Idempotency-Key header. The server checks if it has seen that key before. If yes,
        it returns the stored response. If no, it processes the request, stores the result
        against the key, and returns it. Retries return the cached result without
        reprocessing anything.
      </p>

      <div className="bg-card border border-border rounded-xl p-4 mb-4 not-prose">
        <p className="text-[9px] uppercase tracking-wider text-muted-foreground mb-2">Client side</p>
        <pre className="text-[10px] font-mono bg-muted rounded-xl px-4 py-3 overflow-x-auto leading-relaxed">
{`import uuid, httpx

idempotency_key = str(uuid.uuid4())  # generate once, reuse on every retry

response = httpx.post(
    "/charges",
    json={"amount": 100, "currency": "usd"},
    headers={"Idempotency-Key": idempotency_key},
)
# On timeout or 5xx: retry with the SAME key`}
        </pre>
      </div>

      <div className="bg-card border border-border rounded-xl p-4 mb-6 not-prose">
        <p className="text-[9px] uppercase tracking-wider text-muted-foreground mb-2">Server side</p>
        <pre className="text-[10px] font-mono bg-muted rounded-xl px-4 py-3 overflow-x-auto leading-relaxed">
{`from fastapi import Header
from redis.asyncio import Redis
import json

redis = Redis(decode_responses=True)

@router.post("/charges")
async def create_charge(
    body: ChargeRequest,
    idempotency_key: str = Header(alias="Idempotency-Key"),
):
    cache_key = f"idem:{idempotency_key}"

    cached = await redis.get(cache_key)
    if cached:
        return json.loads(cached)           # return stored result, no reprocessing

    charge = await process_charge(body.amount, body.currency)

    await redis.set(cache_key, json.dumps(charge), ex=86400)  # 24-hour TTL
    return charge`}
        </pre>
      </div>

      <div className="space-y-2 mb-8">
        {KEY_RULES.map(({ rule, detail }) => (
          <div key={rule} className="flex gap-3 p-3 rounded-xl border border-border bg-card">
            <span className="text-primary font-bold text-sm flex-shrink-0 mt-0.5">→</span>
            <div>
              <p className="text-[12px] font-semibold mb-0.5">{rule}</p>
              <p className="text-[11px] text-muted-foreground">{detail}</p>
            </div>
          </div>
        ))}
      </div>

      <h3 className="text-base font-semibold mt-8 mb-3">Database UPSERT</h3>

      <p className="text-[15px] leading-relaxed text-foreground/90 mb-4">
        For operations that map to a single database row, UPSERT is the simpler choice.
        Define a unique constraint on the natural key of the operation, then use INSERT ON
        CONFLICT DO NOTHING. The database enforces exactly-once insertion regardless of
        how many times the operation is attempted.
      </p>

      <div className="bg-card border border-border rounded-xl p-4 mb-8 not-prose">
        <pre className="text-[10px] font-mono bg-muted rounded-xl px-4 py-3 overflow-x-auto leading-relaxed">
{`-- Unique constraint on the natural key
CREATE TABLE order_items (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id    UUID NOT NULL,
    product_id  UUID NOT NULL,
    quantity    INT NOT NULL,
    UNIQUE (order_id, product_id)
);

-- Safe to call multiple times: second call is a no-op
INSERT INTO order_items (order_id, product_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (order_id, product_id) DO NOTHING;

-- Or replace on conflict (idempotent update)
INSERT INTO order_items (order_id, product_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (order_id, product_id)
DO UPDATE SET quantity = EXCLUDED.quantity;`}
        </pre>
      </div>

      <h3 className="text-base font-semibold mt-8 mb-3">Choosing the right pattern</h3>

      <div className="grid gap-3 sm:grid-cols-3">
        {PATTERNS.map(({ pattern, when: w, tradeoff }) => (
          <div key={pattern} className="p-4 bg-card border border-border rounded-xl">
            <p className="text-[12px] font-semibold text-primary mb-1">{pattern}</p>
            <p className="text-[11px] text-muted-foreground mb-2">
              <span className="font-medium text-foreground/80">Use when: </span>
              {w}
            </p>
            <p className="text-[11px] text-muted-foreground">
              <span className="font-medium text-orange-500">Trade-off: </span>
              {tradeoff}
            </p>
          </div>
        ))}
      </div>
    </section>
  );
}
